insert into Item(ItemID, Type, Name, Price, Stock, Manufacturer, Url) values (1, 'Imbracaminte', 'Bluza', 100, 230, 'H&M', '../assets/bluzahm.png');
insert into Item(ItemID, Type, Name, Price, Stock, Manufacturer, Url) values (2, 'Jucarii', 'Puzzle', 15, 130, 'D-Toysss', '../assets/puzzle.png');
insert into Item(ItemID, Type, Name, Price, Stock, Manufacturer, Url) values (3, 'Cosmetice', 'Mascara Lash Sensational', 35, 130, 'Maybelline New York', '../assets/mascara.png');
insert into Item(ItemID, Type, Name, Price, Stock, Manufacturer, Url) values (4, 'Carti', 'Inferno', 25, 230, 'DAO', '../assets/inferno.png');
insert into Item(ItemID, Type, Name, Price, Stock, Manufacturer, Url) values (5, 'Gaming','Tastatura', 250, 210, 'HyperX', '../assets/hyperx.png');
insert into Item(ItemID, Type, Name, Price, Stock, Manufacturer, Url) values (6, 'Carti', 'Harry Potter', 40, 115, 'Arthur', '../assets/harrypotter.jpeg');
insert into Item(ItemID, Type, Name, Price, Stock, Manufacturer, Url) values (7, 'Laptopuri', 'VivoBook 15', 3300, 123, 'Asus', '../assets/asus.png');
insert into Item(ItemID, Type, Name, Price, Stock, Manufacturer, Url) values (8, 'Telefoane', 'Galaxy S21', 3000, 137, 'Samsung', '../assets/samsung.png');
insert into Item(ItemID, Type, Name, Price, Stock, Manufacturer, Url) values (9, 'Gaming', 'Casti', 200, 215, 'Logitech', '../assets/logitech.png');
insert into Item(ItemID, Type, Name, Price, Stock, Manufacturer, Url) values (10, 'Imbracaminte', 'Pantaloni', 90, 320, 'Bershka', '../assets/pantaloni.png');
insert into Item(ItemID, Type, Name, Price, Stock, Manufacturer, Url) values (11, 'Imbracaminte', 'Nike PHANTOM', 259.99, 200, 'Nike', '../assets/Crampoane.JPG');
insert into Item(ItemID, Type, Name, Price, Stock, Manufacturer, Url) values (12, 'Gaming', 'Microsoft Xbox Series X', 4729, 155,  'Microsoft', '../assets/Consola.JPG');
insert into Item(ItemID, Type, Name, Price, Stock, Manufacturer, Url) values (13, 'Carti', 'Biblioteca de la miezul noptii', 32, 89,  'Arthur', '../assets/Carte.JPG');
insert into Item(ItemID, Type, Name, Price, Stock, Manufacturer, Url) values (14, 'Imbracaminte', 'Bluza de molton', 147.90, 213,  'Adidas', '../assets/Hanorac.JPG');
insert into Item(ItemID, Type, Name, Price, Stock, Manufacturer, Url) values (15, 'Laptopuri', 'Laptop HP', 1799, 102, 'HP', '../assets/laptop.JPG');
insert into Item(ItemID, Type, Name, Price, Stock, Manufacturer, Url) values (16, 'Telefoane', 'Galaxy S20', 1899, 84, 'Samsung', '../assets/S20.JPG');
insert into Item(ItemID, Type, Name, Price, Stock, Manufacturer, Url) values (17, 'Jucarii', 'Nava de explorare', 503, 97, 'Disney', '../assets/Lego.jpg');
insert into Item(ItemID, Type, Name, Price, Stock, Manufacturer, Url) values (18, 'Carti', 'Orasul de cenusa', 69, 240, 'Libris', '../assets/orasuldecenusa.png');
insert into Item(ItemID, Type, Name, Price, Stock, Manufacturer, Url) values (19, 'Cosmetice', 'Serum Contur si Volum', 69, 198, 'Cougar', '../assets/serum.png');
insert into Item(ItemID, Type, Name, Price, Stock, Manufacturer, Url) values (20, 'Gaming', 'Controller Wireless Xbox', 290, 101, 'Microsoft', '../assets/controller.png');

insert into Administraor(id,firstName,lastName,username,email,password,address,city,country,zipcode,mobile,fix,landline) values (59,'Eminescu','Mihai','mihaieminescu','mihaiadmin@gmail.com','mihaipass','Str. Zorilor ,nr.12','Bucuresti','Romania',1234,'07555555555','+45555555555','Imi place ciocolata');
insert into Administraor(id,firstName,lastName,username,email,password,address,city,country,zipcode,mobile,fix,landline) values (60,'Blandiana','Anna','annablandiana','annaadmin@gmail.com','annapass','Str. Delfin ,nr.34','Iasi','Romania',7678,'0755442200','+47555544332','Sunt un delfin');
